name: Sync Notion to Jekyll

on:
  schedule:
    - cron: '0 */2 * * *' # 每 2 小时执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install notion-client
    
    - name: Run sync script
      run: |
        NOTION_API_TOKEN=${{ secrets.NOTION_API_TOKEN }} \
        python scripts/sync_notion_to_jekyll.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add _posts/
        git commit -m "Automated sync from Notion" || echo "No changes to commit"
        git push
